"""Tests for evalpower.metrics.

Every expected value below is written as a literal, with the arithmetic that
produces it spelled out in the comment above it. Nothing here is generated by
calling the function under test.
"""

from __future__ import annotations

import math

import pandas as pd
import pytest

from evalpower.metrics import (
    Interval,
    bootstrap_interval,
    interval_disagreement,
    mean_interval_width,
    normal_cdf,
    normal_ppf,
    pass_rate,
    pooled_metrics,
    summarize_dimensions,
    validate_results,
    wilson_interval,
    z_for_confidence,
)

# The 0.975 quantile of the standard normal. Used as the two sided critical
# value for every 95 percent interval in this file.
Z_95 = 1.959963984540054


def test_normal_cdf_at_known_points() -> None:
    # Phi(0) = 0.5 by symmetry of the standard normal about zero.
    assert normal_cdf(0.0) == pytest.approx(0.5, abs=1e-15)
    # Phi(1) = 0.8413447460685429, the standard normal value at one sigma.
    assert normal_cdf(1.0) == pytest.approx(0.8413447460685429, abs=1e-15)
    # Phi(2) = 0.9772498680518208, the standard normal value at two sigma.
    assert normal_cdf(2.0) == pytest.approx(0.9772498680518208, abs=1e-15)
    # Phi(z_0.975) = 0.975 by definition of the quantile.
    assert normal_cdf(Z_95) == pytest.approx(0.975, abs=1e-12)
    # Phi(-z) = 1 - Phi(z), so Phi(-z_0.975) = 0.025.
    assert normal_cdf(-Z_95) == pytest.approx(0.025, abs=1e-12)


def test_normal_ppf_inverts_the_cdf() -> None:
    # Phi is strictly increasing, so ppf(0.5) is the symmetry point, zero.
    assert normal_ppf(0.5) == pytest.approx(0.0, abs=1e-12)
    # ppf(0.8413447460685429) = 1, reading the one sigma value backwards.
    assert normal_ppf(0.8413447460685429) == pytest.approx(1.0, abs=1e-10)
    # ppf(0.9772498680518208) = 2, reading the two sigma value backwards.
    assert normal_ppf(0.9772498680518208) == pytest.approx(2.0, abs=1e-10)
    # ppf(0.025) = -z_0.975 = -1.959963984540054 by symmetry.
    assert normal_ppf(0.025) == pytest.approx(-Z_95, abs=1e-10)
    # Lower tail branch of the approximation, below p_low = 0.02425.
    # ppf(0.01) = -2.3263478740408408, the standard 1 percent normal deviate.
    assert normal_ppf(0.01) == pytest.approx(-2.3263478740408408, abs=1e-10)
    # Upper tail branch, symmetric to the case above.
    assert normal_ppf(0.99) == pytest.approx(2.3263478740408408, abs=1e-10)


def test_normal_ppf_rejects_endpoints() -> None:
    for bad in (0.0, 1.0, -0.1, 1.5):
        with pytest.raises(ValueError):
            normal_ppf(bad)


def test_z_for_confidence() -> None:
    # A 95 percent two sided interval puts 0.025 in each tail, so z is the
    # 0.975 quantile: 1.959963984540054.
    assert z_for_confidence(0.95) == pytest.approx(Z_95, abs=1e-12)
    # A 90 percent two sided interval puts 0.05 in each tail, so z is the
    # 0.95 quantile: 1.6448536269514722.
    assert z_for_confidence(0.90) == pytest.approx(1.6448536269514722, abs=1e-12)
    # A 99 percent two sided interval puts 0.005 in each tail, so z is the
    # 0.995 quantile: 2.5758293035489004.
    assert z_for_confidence(0.99) == pytest.approx(2.5758293035489004, abs=1e-10)


def test_z_for_confidence_rejects_bad_levels() -> None:
    for bad in (0.0, 1.0, -0.5, 2.0):
        with pytest.raises(ValueError):
            z_for_confidence(bad)


def test_pass_rate() -> None:
    assert pass_rate(8, 10) == 0.8
    assert pass_rate(0, 7) == 0.0
    assert pass_rate(7, 7) == 1.0


def test_pass_rate_rejects_impossible_counts() -> None:
    with pytest.raises(ValueError):
        pass_rate(3, 0)
    with pytest.raises(ValueError):
        pass_rate(11, 10)
    with pytest.raises(ValueError):
        pass_rate(-1, 10)


def test_interval_helpers() -> None:
    interval = Interval(0.25, 0.75)
    assert interval.width == 0.5
    assert interval.contains(0.5)
    assert interval.contains(0.25)
    assert interval.contains(0.75)
    assert not interval.contains(0.24)
    assert interval.format(2) == "[0.25, 0.75]"


def test_wilson_interval_eight_of_ten() -> None:
    # p = 8 / 10 = 0.8, n = 10, z = 1.959963984540054
    # z^2         = 3.8414588206941254
    # z^2 / n     = 0.38414588206941254
    # denominator = 1 + 0.38414588206941254 = 1.3841458820694126
    # center      = (0.8 + 3.8414588206941254 / 20) / 1.3841458820694126
    #             = 0.9920729410347063 / 1.3841458820694126
    #             = 0.7167401600411333
    # halfwidth   = (1.959963984540054 / 1.3841458820694126)
    #               * sqrt(0.8 * 0.2 / 10 + 3.8414588206941254 / 400)
    #             = 1.4160096922802283 * sqrt(0.016 + 0.009603647051735313)
    #             = 1.4160096922802283 * sqrt(0.025603647051735313)
    #             = 1.4160096922802283 * 0.16001139663078787
    #             = 0.2265776885044915
    # lower = 0.7167401600411333 - 0.2265776885044915 = 0.4901624715366418
    # upper = 0.7167401600411333 + 0.2265776885044915 = 0.9433178485456248
    interval = wilson_interval(8, 10, 0.95)
    assert interval.lower == pytest.approx(0.4901624715366418, abs=1e-12)
    assert interval.upper == pytest.approx(0.9433178485456248, abs=1e-12)


def test_wilson_interval_at_zero_does_not_collapse() -> None:
    # p = 0 / 20 = 0.0, n = 20, z^2 = 3.8414588206941254
    # z^2 / n     = 0.19207294103470627
    # denominator = 1.1920729410347062
    # center      = (0.0 + 3.8414588206941254 / 40) / 1.1920729410347062
    #             = 0.09603647051735313 / 1.1920729410347062
    #             = 0.08056257902640969
    # halfwidth   = (1.959963984540054 / 1.1920729410347062)
    #               * sqrt(0.0 + 3.8414588206941254 / 1600)
    #             = 1.6441644777532043 * 0.04899909961350135
    #             = 0.08056257902640969
    # lower clips to 0.0, upper = 0.16112515805281938
    interval = wilson_interval(0, 20, 0.95)
    assert interval.lower == pytest.approx(0.0, abs=1e-15)
    assert interval.upper == pytest.approx(0.16112515805281938, abs=1e-12)


def test_wilson_interval_at_one_does_not_collapse() -> None:
    # p = 50 / 50 = 1.0, n = 50, z^2 = 3.8414588206941254
    # z^2 / n     = 0.07682917641388251
    # denominator = 1.0768291764138824
    # center      = (1.0 + 3.8414588206941254 / 100) / 1.0768291764138824
    #             = 1.0384145882069412 / 1.0768291764138824
    #             = 0.9643262004333207
    # halfwidth   = (1.959963984540054 / 1.0768291764138824)
    #               * sqrt(0.0 + 3.8414588206941254 / 10000)
    #             = 1.82012525985527 * 0.01959963984540054
    #             = 0.03567379956667936
    # lower = 0.9286524008666414, upper clips to 1.0
    interval = wilson_interval(50, 50, 0.95)
    assert interval.lower == pytest.approx(0.9286524008666414, abs=1e-12)
    assert interval.upper == pytest.approx(1.0, abs=1e-15)


def test_wilson_interval_is_symmetric_under_relabelling() -> None:
    # Swapping passes for failures reflects the interval about 0.5, because
    # the Wilson formula depends on p only through p and p(1 - p).
    forward = wilson_interval(37, 50, 0.95)
    reversed_labels = wilson_interval(13, 50, 0.95)
    assert forward.lower == pytest.approx(1.0 - reversed_labels.upper, abs=1e-12)
    assert forward.upper == pytest.approx(1.0 - reversed_labels.lower, abs=1e-12)


def test_wilson_interval_narrows_with_more_data() -> None:
    # Same rate, more evidence. The interval width scales roughly as
    # 1 / sqrt(n), so it must strictly shrink.
    widths = [wilson_interval(int(0.9 * n), n, 0.95).width for n in (50, 200, 800)]
    assert widths[0] > widths[1] > widths[2]


def test_bootstrap_interval_is_reproducible() -> None:
    first = bootstrap_interval(43, 50, 0.95, resamples=2000, seed=7)
    second = bootstrap_interval(43, 50, 0.95, resamples=2000, seed=7)
    assert first == second


def test_bootstrap_interval_brackets_the_observed_rate() -> None:
    # The bootstrap distribution is centered on the observed rate, so a
    # percentile interval must contain it.
    interval = bootstrap_interval(43, 50, 0.95, resamples=20000, seed=1)
    assert interval.contains(43 / 50)


def test_bootstrap_interval_collapses_at_a_saturated_rate() -> None:
    # With 50 of 50 passing, every resample of a vector of fifty ones is a
    # vector of fifty ones, so every bootstrap replicate is exactly 1.0.
    interval = bootstrap_interval(50, 50, 0.95, resamples=1000, seed=3)
    assert interval.lower == 1.0
    assert interval.upper == 1.0
    assert interval.width == 0.0


def test_bootstrap_interval_rejects_zero_resamples() -> None:
    with pytest.raises(ValueError):
        bootstrap_interval(8, 10, 0.95, resamples=0)


def test_interval_disagreement_flags_the_collapse() -> None:
    # Wilson keeps a lower bound of 0.9287 at 50 of 50; the bootstrap says
    # 1.0. The gap of 0.0713 is far above the default tolerance.
    wilson = wilson_interval(50, 50, 0.95)
    bootstrap = Interval(1.0, 1.0)
    note = interval_disagreement(wilson, bootstrap, tolerance=0.02)
    assert note is not None
    assert "collapsed" in note


def test_interval_disagreement_is_silent_when_intervals_match() -> None:
    assert interval_disagreement(Interval(0.30, 0.70), Interval(0.31, 0.69), tolerance=0.02) is None


def test_validate_results_normalizes_types() -> None:
    frame = pd.DataFrame(
        {"item_id": [1, 2, 3], "dimension": ["a", "a", "b"], "passed": [1.0, 0.0, 1.0], "extra": [9, 9, 9]}
    )
    validated = validate_results(frame)
    assert list(validated.columns) == ["item_id", "dimension", "passed"]
    assert validated["passed"].tolist() == [1, 0, 1]
    assert validated["dimension"].tolist() == ["a", "a", "b"]


def test_validate_results_rejects_bad_input() -> None:
    with pytest.raises(ValueError, match="missing required column"):
        validate_results(pd.DataFrame({"item_id": [1], "passed": [1]}))
    with pytest.raises(ValueError, match="empty"):
        validate_results(pd.DataFrame({"item_id": [], "dimension": [], "passed": []}))
    with pytest.raises(ValueError, match="must be 0 or 1"):
        validate_results(pd.DataFrame({"item_id": [1], "dimension": ["a"], "passed": [2]}))
    with pytest.raises(ValueError, match="repeated"):
        validate_results(
            pd.DataFrame({"item_id": [1, 1], "dimension": ["a", "a"], "passed": [1, 0]})
        )


def _small_frame() -> pd.DataFrame:
    return pd.DataFrame(
        {
            "item_id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
            "dimension": ["a"] * 5 + ["b"] * 5,
            "passed": [1, 1, 1, 1, 0, 1, 0, 0, 0, 0],
        }
    )


def test_summarize_dimensions_counts_correctly() -> None:
    metrics = summarize_dimensions(validate_results(_small_frame()), resamples=200, seed=0)
    assert [item.dimension for item in metrics] == ["a", "b"]
    # Dimension a has four of five passing, dimension b one of five.
    assert (metrics[0].passes, metrics[0].n, metrics[0].rate) == (4, 5, 0.8)
    assert (metrics[1].passes, metrics[1].n, metrics[1].rate) == (1, 5, 0.2)


def test_pooled_metrics_sums_every_row() -> None:
    pooled = pooled_metrics(validate_results(_small_frame()), resamples=200, seed=0)
    # Five passes out of ten rows across both dimensions.
    assert (pooled.passes, pooled.n, pooled.rate) == (5, 10, 0.5)
    assert pooled.dimension == "ALL"


def test_mean_interval_width_grows_as_evidence_is_split() -> None:
    # The core claim: 600 items on one dimension against the same 600 items
    # spread over 12 dimensions. Splitting does not add data, so the mean
    # interval must widen. Wilson width at n = 600 and p = 0.9 is
    # 2 * 0.024063010817416408 = 0.048126021634832816; at n = 50 and p = 0.9
    # it is far wider, so the ratio is close to sqrt(600 / 50) = 3.4641.
    single = [wilson_interval(540, 600, 0.95)]
    split = [wilson_interval(45, 50, 0.95) for _ in range(12)]
    assert mean_interval_width(single) == pytest.approx(0.048126021634832816, abs=1e-12)
    ratio = mean_interval_width(split) / mean_interval_width(single)
    assert 3.0 < ratio < 4.0
    assert math.isclose(ratio, math.sqrt(12), rel_tol=0.2)


def test_mean_interval_width_requires_dimensions() -> None:
    with pytest.raises(ValueError):
        mean_interval_width([])
